# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5be8bf01eefa3d225a2302df6fa32070759c45392a63c2908e0e2a23a18258ef90cd2af86fa1d24e428f46d67147c9b6b62f23e7d4eb3fdc7910f8d423f78b6

test:
  secret_key_base: 5e108c8039e7b4de94d9ffbc814e2ff001604fc4c256ed970c10a176a818dce04cebc2049d5b6f487b489a8fd760b5df2e7ea6dd1e2b7d4837421f46673c3a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
